### ISSUE TITLE
multi_match not working for me

### ISSUE THREAD

**Issue by marshyski** [trentniemeyer/WanderUI#1]
Hey @trentniemeyer I tried using your Calaca and I couldn't get the multi_match to work.  I configured my index with this...

curl -XGET http://localhost:9200/websites/_search -d '
{
   "query": {
        "multi_match": {
            "query":  "Marshy",
            "type":   "most_fields",
            "fields": [ "title", "body" ]
        }
    }
}'

**Comment by trentniemeyer** [comment]
I can't say this is the best way, but it's the way I was able to get highlight working.  Here is the query done in Marvel.  Dumb question, but I assume that you have 'title' and 'body' in your document?

GET /blogs/blog/_search
{
  "query": {
        "multi_match": {
            "query":  "Marshy",
            "type":   "most_fields", 
            "fields": [ "title", "body" ]
        }
    },
  "highlight": {
    "fields": {
      "*": {}
    }
  },
  "fields": ["highlight"]
}

**Comment by marshyski** [comment]
@trentniemeyer this is my data:

{"title": "Marshy Ski", "url": "http://marshyski.com/", "body": "Blog"}

Here is my mapping for websites my index.

curl -XPUT localhost:9200/websites -d '
{
    "settings": { "number_of_shards": 1 },
    "mappings": {
        "my_type": {
            "properties": {
                "title": {
                    "type":     "string",
                    "analyzer": "english",
                    "fields": {
                        "std":   {
                            "type":     "string",
                            "analyzer": "standard"
                        }
                    }
                }
            }
        }
    }
}'

**Comment by trentniemeyer** [comment]
The reality is that you probably don't need to use the query like I do unless you want highlighting.  Here is my mapping for the blog.  I explicitly mapped body and url

``` javascript
{
   "blogs": {
      "mappings": {
         "blog": {
            "properties": {
               "author": {
                  "type": "nested",
                  "properties": {
                     "blogcount": {
                        "type": "integer"
                     },
                     "id": {
                        "type": "string",
                        "index": "not_analyzed"
                     },
                     "photo": {
                        "type": "string",
                        "index": "not_analyzed"
                     },
                     "url": {
                        "type": "string",
                        "analyzer": "snowball",
                        "fields": {
                           "rawurl": {
                              "type": "string",
                              "index": "not_analyzed"
                           }
                        }
                     },
                     "username": {
                        "type": "string",
                        "index": "not_analyzed"
                     }
                  }
               },
               "body": {
                  "type": "string",
                  "store": true,
                  "analyzer": "snowball"
               },
               "city": {
                  "type": "string",
                  "index": "not_analyzed",
                  "store": true
               },
               "country": {
                  "type": "string",
                  "index": "not_analyzed",
                  "store": true
               },
               "length": {
                  "type": "integer"
               },
               "postdate": {
                  "type": "date",
                  "format": "dateOptionalTime"
               },
               "state": {
                  "type": "string",
                  "index": "not_analyzed",
                  "store": true
               },
               "thumbnailimage": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "title": {
                  "type": "string",
                  "store": true,
                  "analyzer": "snowball",
                  "fields": {
                     "rawtitle": {
                        "type": "string",
                        "index": "not_analyzed"
                     }
                  }
               },
               "trip": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "url": {
                  "type": "string",
                  "analyzer": "snowball",
                  "fields": {
                     "rawurl": {
                        "type": "string",
                        "index": "not_analyzed"
                     }
                  }
               }
            }
         }
      }
   }
}
```

**Comment by marshyski** [comment]
Ah makes sense now.  Thanks for the input @trentniemeyer !  You can close this now.

**Comment by trentniemeyer** [comment]
No problem.  Take a look at my BlogParse repo.   That has the mappings in there, I used elasticssearch_dsl to define the document structure.  So far I like it.  https://github.com/trentniemeyer/BlogParse/blob/master/ElasticMappings.py
